### ISSUE TITLE
No macos-x86_64.zip for version 0.0.9

### ISSUE THREAD

**Issue by thecontinium** [mickael-menu/zk#128]
The latest [release](https://github.com/mickael-menu/zk/releases/tag/v0.9.0) for macOS x86_64 seems to be missing ?

**Comment by mickael-menu** [comment]
Yeah unfortunately I don't have access to an Intel mac until next year. I'll take a look if there's a way to build it from M1, otherwise you can build from source or try the [Homebrew tap](https://github.com/mhanberg/homebrew-zk).

**Comment by thecontinium** [comment]
That’s a pity. I’m adding zk [here](https://github.com/thecontinium/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/zk/init.lua#L1) to allow install and load in the same manner as all the other servers I use. If you like I can build it for you; just let me know how and I’ll give it a go ?

**Comment by mickael-menu** [comment]
Sure, that would be helpful. Unless there's a critical bug I don't think I'll do another release before I get my hands back onto my Intel mac.

To build on macOS you need Go and the `icu4c` lib, you can see the instructions to install this in this section: https://github.com/mickael-menu/zk#on-macos

You can generate the release ZIP with `make dist-macos`

I took a look at generating from the M1 but it's quite complicated because of the dependencies on C libraries.

**Comment by thecontinium** [comment]
Here is the build (git checkout v0.9.0; make mac-dist) from an intel mac [zk-v0.9.0-macos-x86_64.zip](https://github.com/mickael-menu/zk/files/7744138/zk-v0.9.0-macos-x86_64.zip)

If you add it to the release page I can test the zk install for [nvim-lsp-installer](https://github.com/thecontinium/nvim-lsp-installer)

Cheers.

**Comment by mickael-menu** [comment]
Thanks! It's added
