### ISSUE TITLE
fzf key binding overrides

### ISSUE THREAD

**Issue by megalithic** [mickael-menu/zk#179]
Hey there @mickael-menu! Great progress you've made; I've been using `zk` more recently and noticed you have some provisions added for being able to configure the "tool" (fzf) bindings, mostly I just want to override, `ctrl-n` to be the default `down` action, and handle the new note capability with `ctrl-c` instead.

Any examples for this? I didn't see any tests for this in config_test.go spec. Thanks much!

It'd be super awesome to start showing all possible config options in some "mega-config" example. Wishful thinking, as I'm sure you have enough on your plate.

Thanks!!

**Comment by mickael-menu** [comment]
Hi @megalithic, thanks! Sorry for the delay answering. As you've already seen it's not yet supported but will be eventually in #154 .

> It'd be super awesome to start showing all possible config options in some "mega-config" example. Wishful thinking, as I'm sure you have enough on your plate.

Right now when you do `zk init` you get a fully commented example in `.zk/config.toml`. Is this what you had in mind?

Otherwise I made sure to document every config property in the linked Markdown here: https://github.com/mickael-menu/zk/blob/main/docs/config.md But maybe the documentation is not clear enough or a bit confusing?
