### ISSUE TITLE
bat: command not found

### ISSUE THREAD

**Issue by jfvillablanca** [mickael-menu/zk#272]
Hello, I am trying to configure zk config toml (following the docs [[1]](https://github.com/mickael-menu/zk/blob/main/docs/tool-fzf.md)[[2]](https://github.com/mickael-menu/zk/blob/main/docs/config.md)), I uncommented `fzf-preview = "bat -p --color always {-1}"` from the toml.

Installed bat via apt so I created an alias in my .bashrc

```
alias bat=batcat
alias cat=batcat
```

Whenever I launch `zk list -i`, fzf fails to render the file as seen on the screenshot below.

![Screenshot from 2022-11-24 15-06-37](https://user-images.githubusercontent.com/31008330/203716496-7c9dc19e-7d32-42cf-830b-9275f938e986.png)

I also tried removing the alias from the .bashrc just in case it was interfering with fzf or zk. Still similar behavior.

Please point me in the right direction on what could I have possibly missed. Thanks

**Comment by mickael-menu** [comment]
Are you able to run `bat` with `fzf` directly with: `fzf --preview 'bat -p --color always {}'`?

**Comment by UnkwUsr** [comment]
Alias `bat=batcat` is set only inside your shell (bash). Other programs looks for programs in paths described in `$PATH` environment variable. So you have 2 options:

1. Simply modify zk toml config to use directly `batcat`, not `bat`.
2. Make symlink `bat` to `/bin/batcat` and place it to some path described in `$PATH`.

Also second option will allow you to use `bat` instead of `batcat` from any other program.

**Comment by jfvillablanca** [comment]
Thank you @UnkwUsr and @mickael-menu for the responses.

I forgot that .bashrc is not sourced by other programs. I did the symlink solution and everything works fine now 🙂
