### ISSUE TITLE
Is it possible to list all defined tags?

### ISSUE THREAD

**Issue by becarepsol** [mickael-menu/zk#84]
I was wondering if it is possible to list all user defined tags, as of now it is
possible to list all notes that include the specified tags; but I'm not sure if
it's possible to list all defined tags.

I want to be able to output all tags as a list so I can feed them as a source
to a picker in my text editor and make sure that I'm using a consistent set of
tags

Thanks

**Comment by mickael-menu** [comment]
Not yet but I planned to add this feature, so that's a good opportunity. Here's a working implementation, but I have to finish some stuff before merging (including adding a sorting flag). I'll probably get this merged next week: https://github.com/mickael-menu/zk/pull/85

Take a look at the formatting flags to pair it with your text editor, it's quite customizable. This might be useful for you:

```sh
zk tag list --quiet --no-pager --format name
```

There's also a `--format json` option.

**Comment by mickael-menu** [comment]
Actually I merged it already, so it's available in `main`.
