### ISSUE TITLE
zk does not recognize my Wiki link template with a pipe

### ISSUE THREAD

**Issue by nogweii** [mickael-menu/zk#98]
Here is part of my configuration:

```toml
[note]
filename = "{{slug title}}.{{id}}"

[format.markdown]
link-format = "[[{{metadata.id}}|{{title}}]]"
```

This generates a text link from the LSP something like this:

```
[[ker6z|Terms of Gardening]]
```

But it does not get recognized as an actual link to the note:

```bash
$ zk list -l Digital\ Garden/terms-of-gardening.ker6z.md
Found 0 note
```

My intention with the template is to be able to link to a template without worrying what its filename is as well as enabling custom link text in the source document to allow better flow in whatever context it is in.

For me, when "wiki" is listed as a supported link style, I expected nearly-full support of [MediaWiki's link syntax](https://en.wikipedia.org/wiki/Help:Link) but it seems it's much simpler then that. Could this feature be added?

**Comment by mickael-menu** [comment]
This should be supported already. I won't have time to test before next week though.

**Comment by nogweii** [comment]
did some experimenting:

### These aren't detected as links at all (no LSP hints at all)

```
[[ker6z|these terms]]
[[.ker6z|these terms]]
[[ker6z.|foo]]
```

### These get detected as a link, but result in 'not found' LSP indicators
```
[[ker6z | these terms]]
[[these terms|ker6z]]
[[these terms | ker6z]]
[[.ker6z | these terms]]
```

### These work as expected

```
[[Terms of Gardening]]
[[Digital Garden/terms-of-gardening.ker6z]]
[[.ker6z]]
[[ker6z]]
[[ker6z.]]
```

**Comment by nogweii** [comment]
I hope this makes it a bit easier, here is a repo to reproduce the error: https://github.com/nogweii/zk-issues-98

**Comment by mickael-menu** [comment]
Thanks, I'll take a look this weekend

**Comment by mickael-menu** [comment]
@nogweii Thanks, your sample repo was very helpful.

There's actually several issues:

* The LSP hints are not always reported depending on the type of links. I didn't look into this yet.
* The first one you reported where `--link-to`/`--linked-by` would not work with your wiki links. The issue is that I was matching for a path prefix no matter which type of links was parsed. I fixed this in the following PR to match any portion of a path for wiki links. Let me know if that helps:
https://github.com/mickael-menu/zk/pull/104

**Comment by mickael-menu** [comment]
I fixed the LSP hints/diagnostics in the same PR, there were two issues:

* Spaces around the pipe were not ignored.
* I intentionally avoided sending LSP diagnostics if a wiki link had a title (pipe), as I thought it was redundant. But from your examples I realised it was useful so I enabled them.

The only two cases I didn't fix because they are correct are the following from your repo:

```md
[Terms of Gardening](terms-of-gardening.ker6z)
[Terms of Gardening](ker6z)
```

Markdown links are equivalent to HTML `<a>` links so it's normal that you can't find these notes as they are located in a sub-folder.

I'll wait for you to test the changes before merging this PR.
